#Browser Configuration
browser=Chrome
#Application URL
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#Credentials
Username=admin
password=admin123
#implicitwait(in seconds)
implicitWait=10