#Browser Configuration
browser=chrome
#Application URL
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#Credentials
Username=admin
password=admin123
#implicitwait(in seconds)
implicitWait=10
#Dynamic wait
timeout=30
explicit=30
